version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src-php-fpm:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src-nginx:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "4433:443"
    depends_on:
      - php-fpm
  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
      # - ./mysql-data:/var/lib/mysql
# volumes:
#   mysql-data:
